# Make sure that the databases are exactly the same before running Axium.

services:
  # HAProxy Load Balancer for Axium
  axiumloadbalancer:
    # Use the latest HAProxy image
    image: haproxy:latest
    # Map port 80 from the container to the host machine
    ports:
      - "80:80"
    command:
      - /bin/sh
      - -c
      - |
        cat > /usr/local/etc/haproxy/haproxy.cfg << EOF
        global
          daemon
          maxconn 256

        defaults
          mode http
          timeout connect 5000ms
          timeout client 50000ms
          timeout server 50000ms

        frontend http-in
          bind *:80
          default_backend servers

        backend servers
          balance roundrobin
          server server1 axium:3000 check
          server server2 axium2:3001 check
        EOF
        haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    # Depend on the Axium services and wait until they're ready
    # Depend on both PostgreSQL databases and wait until they're healthy
    depends_on:
      axium:
        condition: service_healthy
      axium2:
        condition: service_healthy

  # Service for the Axium application
  axium:
    # Build the Docker image from the current directory using the specified Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Map ports from the container to the host machine
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}" # Expose server port

    # Environment variables for the service
    environment:
      # General Configuration
      - ENVIRONMENT=${ENVIRONMENT:-development}

      # Server Configuration
      - SERVER_IP=${SERVER_IP:-127.0.0.1}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - SERVER_TRACE_ENABLED=${SERVER_TRACE_ENABLED:-true}
      - SERVER_WORKER_THREADS=${SERVER_WORKER_THREADS:-2}

      # Database Configuration
      - DATABASE_URL=${DATABASE_URL:-postgres://dbuser:1234@localhost/axium}
      - DATABASE_USER=${DATABASE_USER:-dbuser}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-1234}
      - DATABASE_DB=${DATABASE_DB:-axium}
      - DATABASE_MAX_CONNECTIONS=${DATABASE_MAX_CONNECTIONS:-20}
      - DATABASE_MIN_CONNECTIONS=${DATABASE_MIN_CONNECTIONS:-5}

      # Storage Configuration (MinIO/S3)
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT:-http://storage}
      - STORAGE_PORT=${STORAGE_PORT:-9000}
      - STORAGE_CONSOLE_PORT=${STORAGE_CONSOLE_PORT:-9001}
      - STORAGE_REGION=${STORAGE_REGION:-us-east-1}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY:-minioadmin}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY:-minioadmin}
      - STORAGE_BUCKET_PROFILE_PICTURES=${STORAGE_BUCKET_PROFILE_PICTURES:-profile-pictures}

      # HTTPS Configuration
      - SERVER_HTTPS_ENABLED=${SERVER_HTTPS_ENABLED:-false}
      - SERVER_HTTPS_HTTP2_ENABLED=${SERVER_HTTPS_HTTP2_ENABLED:-true}
      - SERVER_HTTPS_CERT_FILE_PATH=${SERVER_HTTPS_CERT_FILE_PATH:-/app/certs/cert.pem}
      - SERVER_HTTPS_KEY_FILE_PATH=${SERVER_HTTPS_KEY_FILE_PATH:-/app/certs/key.pem}

      # Rate Limit Configuration
      - SERVER_RATE_LIMIT=${SERVER_RATE_LIMIT:-5}
      - SERVER_RATE_LIMIT_PERIOD=${SERVER_RATE_LIMIT_PERIOD:-1}

      # Compression Configuration
      - SERVER_COMPRESSION_ENABLED=${SERVER_COMPRESSION_ENABLED:-true}
      - SERVER_COMPRESSION_LEVEL=${SERVER_COMPRESSION_LEVEL:-6}

      # Authentication Configuration (JWT)
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-Change me!}
      - JWT_ISSUER=${JWT_ISSUER:-your_issuer}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-your_audience}
      - JWT_ALLOW_COOKIE_AUTH=${JWT_ALLOW_COOKIE_AUTH:-true}
      - JWT_FORCE_COOKIE_AUTH=${JWT_FORCE_COOKIE_AUTH:-false}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME:-auth_token}
      - JWT_COOKIE_MAX_AGE=${JWT_COOKIE_MAX_AGE:-604800}
      - JWT_COOKIE_SAMESITE=${JWT_COOKIE_SAMESITE:-Lax}

      # CORS Configuration
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN:-http://127.0.0.1:3000}
      - CORS_ALLOW_METHODS=${CORS_ALLOW_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      - CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS:-Authorization,Content-Type,Origin}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS:-true}
      - CORS_MAX_AGE=${CORS_MAX_AGE:-3600}

      # Redis Configuration
      - CACHE_ENDPOINT=${CACHE_ENDPOINT:-127.0.0.1}
      - CACHE_PORT=${CACHE_PORT:-6379}
      - CACHE_USERNAME=${CACHE_USERNAME:-}
      - CACHE_PASSWORD=${CACHE_PASSWORD:-}
      - CACHE_DB=${CACHE_DB:-0}

    # Depend on the pgpool service and wait until it's healthy
    depends_on:
      pgpool:
        condition: service_healthy
      storageloadbalancer:
        condition: service_healthy
      cache:
        condition: service_healthy

    # Mount volumes for certificates
    volumes:
      - ./certs:/app/certs  # Mount local certs directory to container

    # Health check settings
    healthcheck:
      # Test the health of the service by checking the /health endpoint
      test: ["CMD", "curl", "-f", "http://${SERVER_IP:-0.0.0.0}:${SERVER_PORT:-3000}/health"]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Timeout after 5 seconds
      retries: 3 # Retry up to 3 times
      start_period: 15s # Wait 15 seconds before starting checks

    # Resource limits for the service
    deploy:
      resources:
        limits:
          # Limit CPU usage (default: 0.5 cores)
          cpus: '${AXIUM_CPU_LIMIT:-0.5}'
          # Limit RAM usage (default: 512MB)
          memory: ${AXIUM_MEMORY_LIMIT:-512M}

  # Second instance of Axium application
  axium2:
    # Use the same build configuration as the first instance. Haven't found a way to bypass having to build the second container.
    build:
      context: .
      dockerfile: Dockerfile
    # Use the same environment variables and other settings as the first instance
    environment:
      - SERVER_PORT=${SERVER2_PORT:-3001} # Use a different port
    ports:
      - "${SERVER2_PORT:-3001}:${SERVER2_PORT:-3001}"
    depends_on:
      pgpool:
        condition: service_healthy
      storageloadbalancer:
        condition: service_healthy
      cache:
        condition: service_healthy
    # Health check settings
    healthcheck:
      # Test the health of the service by checking the /health endpoint
      test: ["CMD", "curl", "-f", "http://${SERVER2_IP:-0.0.0.0}:${SERVER2_PORT:-3001}/health"]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Timeout after 5 seconds
      retries: 3 # Retry up to 3 times
      start_period: 15s # Wait 15 seconds before starting checks
    # Resource limits for the service
    deploy:
      resources:
        limits:
          # Limit CPU usage (default: 0.5 cores)
          cpus: '${AXIUM_CPU_LIMIT:-0.5}'
          # Limit RAM usage (default: 512MB)
          memory: ${AXIUM_MEMORY_LIMIT:-512M}

  # PostgreSQL connection pooler
  pgpool:
    # Use the Bitnami Pgpool-II image
    image: bitnami/pgpool:4.6.0
    # Map port 5432 from the container to the host machine
    ports:
      - "5432:5432"
    # Environment variables for the service
    environment:
      - PGPOOL_BACKEND_NODES=0:db:5432,1:db2:5432
      - PGPOOL_SR_CHECK_USER=${DATABASE_USER:-dbuser}
      - PGPOOL_SR_CHECK_PASSWORD=${DATABASE_PASSWORD:-1234}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_MAX_POOL=20
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME:-pgpooladmin} # Add admin username
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD:-adminpassword} # Add admin password
      - PGPOOL_POSTGRES_USERNAME=${DATABASE_USER:-dbuser} # Add Postgres username
      - PGPOOL_POSTGRES_PASSWORD=${DATABASE_PASSWORD:-1234} # Add Postgres password
    # Depend on both PostgreSQL databases and wait until they're healthy
    depends_on:
      db:
        condition: service_healthy
      db2:
        condition: service_healthy
    # Health check settings
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Primary PostgreSQL database
  db:
    # Use the official PostgreSQL 17 Alpine image
    image: postgres:17-alpine
    # Always restart the container if it fails
    restart: always
    ports:
      - "5433:5432"
    # Environment variables for the database
    environment:
      - POSTGRES_USER=${DATABASE_USER:-dbuser}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-1234}
      - POSTGRES_DB=${DATABASE_DB:-axium}
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
    # Mount volumes for database data and logs
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/logs:/var/log/postgresql
    # Health check settings for the database
    healthcheck:
      # Test the health of the database using pg_isready
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER:-dbuser}"]
      interval: 60s # Check every minute
      timeout: 10s # Timeout after 10 seconds
      retries: 5 # Retry up to 5 times
      start_period: 15s # Wait 15 seconds before starting checks
    # Resource limits for the database service
    deploy:
      resources:
        limits:
          # Limit CPU usage (default: 0.5 cores)
          cpus: '${DB_CPU_LIMIT:-0.5}'
          # Limit RAM usage (default: 256MB)
          memory: ${DB_MEMORY_LIMIT:-256M}

  # Secondary PostgreSQL database for failover
  db2:
    # Use the official PostgreSQL 17 Alpine image
    image: postgres:17-alpine
    # Always restart the container if it fails
    restart: always
    ports:
      - "5434:5432" # Different port for the slave database
    # Environment variables for the database
    environment:
      - POSTGRES_USER=${DATABASE_USER:-dbuser}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-1234}
      - POSTGRES_DB=${DATABASE_DB:-axium}
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
    # Mount volumes for database data and logs
    volumes:
      - ./docker/db2/data:/var/lib/postgresql/data
      - ./docker/db2/logs:/var/log/postgresql
    # Health check settings for the database
    healthcheck:
      # Test the health of the database using pg_isready
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER:-dbuser}"]
      interval: 60s # Check every minute
      timeout: 10s # Timeout after 10 seconds
      retries: 5 # Retry up to 5 times
      start_period: 15s # Wait 15 seconds before starting checks
    # Resource limits for the database service
    deploy:
      resources:
        limits:
          # Limit CPU usage (default: 0.5 cores)
          cpus: '${DB_CPU_LIMIT:-0.5}'
          # Limit RAM usage (default: 256MB)
          memory: ${DB_MEMORY_LIMIT:-256M}

  # HAProxy Load Balancer for the storage services
  storageloadbalancer:
    # Use the latest HAProxy image
    image: haproxy:latest
    # Map port 80 from the container to the host machine
    ports:
      - "9000:9000"
    command:
      - /bin/sh
      - -c
      - |
        cat > /usr/local/etc/haproxy/haproxy.cfg << EOF
        global
          daemon
          maxconn 256

        defaults
          mode http
          timeout connect 5000ms
          timeout client 50000ms
          timeout server 50000ms

        frontend http-in
          bind *:9000
          default_backend servers

        backend servers
          balance roundrobin
          server server1 storage:9001 check
          server server2 storage2:9002 check
        EOF
        haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    # Depend on the Axium services and wait until they're ready
    # Depend on both PostgreSQL databases and wait until they're healthy
    depends_on:
      storage:
        condition: service_healthy
      storage2:
        condition: service_healthy



  storage:
    image: minio/minio
    command: server --console-address ":9011" --address ":9001" /data
    ports:
     - "9001:9001"
     - "9011:9011"
    environment:
      - MINIO_ROOT_USER=${STORAGE_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET_KEY:-minioadmin}
    volumes:
      - ./docker/minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  storage2:
    image: minio/minio
    command: server --console-address ":9012" --address ":9002" /data
    ports:
     - "9002:9002"
     - "9012:9012"
    environment:
      - MINIO_ROOT_USER=${STORAGE_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET_KEY:-minioadmin}
    volumes:
      - ./docker/minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Redis Service, for a full failover system use: redis sentinel.
  cache:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis port
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD:-}  # Set Redis password if configured
      - REDIS_USER=${CACHE_USERNAME:-}  # Redis username if applicable
      - REDIS_DB=${CACHE_DB:-0}  # Default Redis DB
    volumes:
      - ./docker/cache/data:/data  # Persist Redis data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "${CACHE_PORT:-6379}", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M