use std::collections::HashMap;
use std::sync::OnceLock;

pub static LANGUAGE_NAMES: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

pub fn languages() -> &'static HashMap<&'static str, &'static str> {
    LANGUAGE_NAMES.get_or_init(|| {
        HashMap::from([
            ("af-ZA", "Afrikaans (Suid-Afrika)"),
            ("am-ET", "አማርኛ (ኢትዮጵያ)"),
            ("ar-SA", "العربية (السعودية)"),
            ("as-IN", "অসমীয়া (ভাৰত)"),
            ("az-AZ", "Azərbaycanca (Azərbaycan)"),
            ("be-BY", "Беларуская (Беларусь)"),
            ("bg-BG", "Български (България)"),
            ("bn-BD", "বাংলা (বাংলাদেশ)"),
            ("bn-IN", "বাংলা (ভারত)"),
            ("bs-BA", "Bosanski (Bosna i Hercegovina)"),
            ("ca-ES", "Català (Espanya)"),
            ("cs-CZ", "Čeština (Česko)"),
            ("cy-GB", "Cymraeg (Y Deyrnas Unedig)"),
            ("da-DK", "Dansk (Danmark)"),
            ("de-AT", "Deutsch (Österreich)"),
            ("de-CH", "Deutsch (Schweiz)"),
            ("de-DE", "Deutsch (Deutschland)"),
            ("el-GR", "Ελληνικά (Ελλάδα)"),
            ("en-AU", "English (Australia)"),
            ("en-CA", "English (Canada)"),
            ("en-GB", "English (United Kingdom)"),
            ("en-IE", "English (Ireland)"),
            ("en-IN", "English (India)"),
            ("en-NZ", "English (New Zealand)"),
            ("en-US", "English (United States)"),
            ("es-AR", "Español (Argentina)"),
            ("es-CL", "Español (Chile)"),
            ("es-CO", "Español (Colombia)"),
            ("es-ES", "Español (España)"),
            ("es-MX", "Español (México)"),
            ("es-US", "Español (Estados Unidos)"),
            ("et-EE", "Eesti (Eesti)"),
            ("eu-ES", "Euskara (Espainia)"),
            ("fa-IR", "فارسی (ایران)"),
            ("fi-FI", "Suomi (Suomi)"),
            ("fil-PH", "Filipino (Pilipinas)"),
            ("fr-BE", "Français (Belgique)"),
            ("fr-CA", "Français (Canada)"),
            ("fr-CH", "Français (Suisse)"),
            ("fr-FR", "Français (France)"),
            ("ga-IE", "Gaeilge (Éire)"),
            ("gl-ES", "Galego (España)"),
            ("gu-IN", "ગુજરાતી (ભારત)"),
            ("he-IL", "עברית (ישראל)"),
            ("hi-IN", "हिन्दी (भारत)"),
            ("hr-HR", "Hrvatski (Hrvatska)"),
            ("hu-HU", "Magyar (Magyarország)"),
            ("hy-AM", "Հայերեն (Հայաստան)"),
            ("id-ID", "Bahasa Indonesia (Indonesia)"),
            ("is-IS", "Íslenska (Ísland)"),
            ("it-CH", "Italiano (Svizzera)"),
            ("it-IT", "Italiano (Italia)"),
            ("ja-JP", "日本語 (日本)"),
            ("jv-ID", "Basa Jawa (Indonesia)"),
            ("ka-GE", "ქართული (საქართველო)"),
            ("kk-KZ", "Қазақ тілі (Қазақстан)"),
            ("km-KH", "ខ្មែរ (កម្ពុជា)"),
            ("kn-IN", "ಕನ್ನಡ (ಭಾರತ)"),
            ("ko-KR", "한국어 (대한민국)"),
            ("lo-LA", "ລາວ (ປະເທດລາວ)"),
            ("lt-LT", "Lietuvių (Lietuva)"),
            ("lv-LV", "Latviešu (Latvija)"),
            ("mk-MK", "Македонски (Македонија)"),
            ("ml-IN", "മലയാളം (ഭാരതം)"),
            ("mn-MN", "Монгол (Монгол улс)"),
            ("mr-IN", "मराठी (भारत)"),
            ("ms-MY", "Bahasa Melayu (Malaysia)"),
            ("my-MM", "မြန်မာ (မြန်မာ)"),
            ("nb-NO", "Norsk Bokmål (Norge)"),
            ("ne-NP", "नेपाली (नेपाल)"),
            ("nl-BE", "Nederlands (België)"),
            ("nl-NL", "Nederlands (Nederland)"),
            ("nn-NO", "Norsk Nynorsk (Noreg)"),
            ("or-IN", "ଓଡ଼ିଆ (ଭାରତ)"),
            ("pa-IN", "ਪੰਜਾਬੀ (ਭਾਰਤ)"),
            ("pl-PL", "Polski (Polska)"),
            ("ps-AF", "پښتو (افغانستان)"),
            ("pt-BR", "Português (Brasil)"),
            ("pt-PT", "Português (Portugal)"),
            ("ro-RO", "Română (România)"),
            ("ru-RU", "Русский (Россия)"),
            ("sd-PK", "سنڌي (پاڪستان)"),
            ("si-LK", "සිංහල (ශ්‍රී ලංකාව)"),
            ("sk-SK", "Slovenčina (Slovensko)"),
            ("sl-SI", "Slovenščina (Slovenija)"),
            ("so-SO", "Soomaali (Soomaaliya)"),
            ("sq-AL", "Shqip (Shqipëri)"),
            ("sr-RS", "Српски (Србија)"),
            ("sv-SE", "Svenska (Sverige)"),
            ("sw-KE", "Kiswahili (Kenya)"),
            ("ta-IN", "தமிழ் (இந்தியா)"),
            ("te-IN", "తెలుగు (భారత దేశం)"),
            ("th-TH", "ไทย (ประเทศไทย)"),
            ("tr-TR", "Türkçe (Türkiye)"),
            ("uk-UA", "Українська (Україна)"),
            ("ur-PK", "اردو (پاکستان)"),
            ("uz-UZ", "Oʻzbek (Oʻzbekiston)"),
            ("vi-VN", "Tiếng Việt (Việt Nam)"),
            ("zh-CN", "中文 (中国)"),
            ("zh-HK", "中文 (香港)"),
            ("zh-TW", "中文 (台灣)"),
            ("zu-ZA", "isiZulu (iNingizimu Afrika)"),
        ])
    })
}