name: coverage

on: 
  push:
    branches:
      - main  # Adjust if you have different branches you want to trigger this on

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Generate code coverage with Tarpaulin
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      # Step 3: Upload to Coveralls
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Make sure to store your token in GitHub Secrets
        run: |
          curl -s https://coveralls.io/github/Riktastic/Axium?service=github-actions&token=${{ secrets.COVERALLS_REPO_TOKEN }} -d coverage=@target/debug/coverage.xml
